import {
  BarChart3,
  BookOpen,
  BriefcaseBusiness,
  CalendarDays,
  ClipboardCheck,
  CreditCard,
  GitBranch,
  FileText,
  GraduationCap,
  LayoutDashboard,
  MessageSquare,
  Settings,
  Sparkles,
  UserCheck,
  UserRoundCog,
  Users
} from "lucide-react";
import type { NavItem } from "@/types/ui.types";

export const navigationItems: NavItem[] = [
  { title: "Dashboard", href: "/admin", icon: LayoutDashboard, roles: ["super_admin", "school_admin"], section: "Main" },
  { title: "Admissions", href: "/admin/admissions", icon: UserCheck, roles: ["super_admin", "school_admin"], section: "Front Office" },
  { title: "Recruitment", href: "/admin/recruitment", icon: BriefcaseBusiness, roles: ["super_admin", "school_admin"], section: "Front Office" },
  { title: "Students", href: "/admin/students", icon: GraduationCap, roles: ["super_admin", "school_admin"], section: "Front Office" },
  { title: "Student 360", href: "/admin/student-360", icon: Sparkles, roles: ["super_admin", "school_admin"], section: "Front Office" },
  { title: "Staff", href: "/admin/staff", icon: Users, roles: ["super_admin", "school_admin"], section: "Front Office" },
  { title: "User Management", href: "/admin/access", icon: UserRoundCog, roles: ["super_admin", "school_admin"], section: "Front Office" },
  { title: "Automation", href: "/admin/automation", icon: GitBranch, roles: ["super_admin", "school_admin"], section: "Front Office" },
  { title: "Attendance", href: "/admin/attendance", icon: ClipboardCheck, roles: ["super_admin", "school_admin"], section: "Academics" },
  { title: "Grades", href: "/admin/grades", icon: BarChart3, roles: ["super_admin", "school_admin"], section: "Academics" },
  { title: "Reports", href: "/admin/reports", icon: FileText, roles: ["super_admin", "school_admin"], section: "Academics" },
  { title: "Fees", href: "/admin/fees", icon: CreditCard, roles: ["super_admin", "school_admin"], section: "Operations" },
  { title: "HR Suite", href: "/hr", icon: Users, roles: ["super_admin", "school_admin", "hr_staff"], section: "Operations" },
  { title: "Finance Suite", href: "/finance", icon: CreditCard, roles: ["super_admin", "school_admin", "finance_officer"], section: "Operations" },
  { title: "Library Suite", href: "/library", icon: BookOpen, roles: ["super_admin", "school_admin", "librarian"], section: "Operations" },
  { title: "IT Desk", href: "/it", icon: Settings, roles: ["super_admin", "school_admin", "it_support"], section: "Operations" },
  { title: "Settings", href: "/admin/settings", icon: Settings, roles: ["super_admin", "school_admin"], section: "Settings & Support" },

  { title: "Dashboard", href: "/hr", icon: LayoutDashboard, roles: ["hr_staff"], section: "Main" },
  { title: "Staff Profiles", href: "/hr/staff", icon: Users, roles: ["hr_staff"], section: "People" },
  { title: "Leave", href: "/hr/leave", icon: CalendarDays, roles: ["hr_staff"], section: "People" },
  { title: "Recruitment", href: "/hr/recruitment", icon: UserRoundCog, roles: ["hr_staff"], section: "People" },
  { title: "Documents", href: "/hr/documents", icon: FileText, roles: ["hr_staff"], section: "People" },
  { title: "Tasks", href: "/hr/tasks", icon: GitBranch, roles: ["hr_staff"], section: "People" },
  { title: "Payroll", href: "/hr/payroll", icon: CreditCard, roles: ["hr_staff"], section: "Operations" },

  { title: "Dashboard", href: "/finance", icon: LayoutDashboard, roles: ["finance_officer"], section: "Main" },
  { title: "Daily Payments", href: "/finance/payments", icon: CreditCard, roles: ["finance_officer"], section: "Finance" },
  { title: "Daily Fee Plans", href: "/finance/billing-batches", icon: ClipboardCheck, roles: ["finance_officer"], section: "Finance" },
  { title: "Special Invoices", href: "/finance/invoices", icon: FileText, roles: ["finance_officer"], section: "Finance" },
  { title: "Expenses", href: "/finance/expenses", icon: BarChart3, roles: ["finance_officer"], section: "Finance" },
  { title: "Collections", href: "/finance/collections", icon: GitBranch, roles: ["finance_officer"], section: "Finance" },
  { title: "Payroll", href: "/finance/payroll", icon: Users, roles: ["finance_officer"], section: "Finance" },

  { title: "Dashboard", href: "/library", icon: LayoutDashboard, roles: ["librarian"], section: "Main" },
  { title: "Catalog", href: "/library/catalog", icon: BookOpen, roles: ["librarian"], section: "Library" },
  { title: "Copies", href: "/library/copies", icon: FileText, roles: ["librarian"], section: "Library" },
  { title: "Loans", href: "/library/loans", icon: ClipboardCheck, roles: ["librarian"], section: "Library" },
  { title: "Fines", href: "/library/fines", icon: CreditCard, roles: ["librarian"], section: "Library" },
  { title: "Tasks", href: "/library/library-tasks", icon: GitBranch, roles: ["librarian"], section: "Library" },

  { title: "Dashboard", href: "/it", icon: LayoutDashboard, roles: ["it_support"], section: "Main" },
  { title: "Devices", href: "/it/devices", icon: Settings, roles: ["it_support"], section: "Technology" },
  { title: "Tickets", href: "/it/tickets", icon: ClipboardCheck, roles: ["it_support"], section: "Technology" },
  { title: "Integrations", href: "/it/integrations", icon: Sparkles, roles: ["it_support"], section: "Technology" },
  { title: "Automation", href: "/it/automation", icon: GitBranch, roles: ["it_support"], section: "Technology" },
  { title: "Messages", href: "/it/messages", icon: MessageSquare, roles: ["it_support"], section: "Technology" },
  { title: "Audit Log", href: "/it/audit", icon: FileText, roles: ["it_support"], section: "Technology" },

  { title: "Dashboard", href: "/teacher", icon: LayoutDashboard, roles: ["teacher"], section: "Main" },
  { title: "Classes", href: "/teacher/classes", icon: BookOpen, roles: ["teacher"], section: "Teaching" },
  { title: "Student 360", href: "/teacher/student-360", icon: Sparkles, roles: ["teacher"], section: "Teaching" },
  { title: "Attendance", href: "/teacher/attendance", icon: ClipboardCheck, roles: ["teacher"], section: "Teaching" },
  { title: "Grades", href: "/teacher/grades", icon: BarChart3, roles: ["teacher"], section: "Teaching" },
  { title: "Assignments", href: "/teacher/assignments", icon: FileText, roles: ["teacher"], section: "Teaching" },
  { title: "Lesson Planner", href: "/teacher/lesson-planner", icon: Sparkles, roles: ["teacher"], section: "Teaching" },

  { title: "Dashboard", href: "/student", icon: LayoutDashboard, roles: ["student"], section: "Main" },
  { title: "Assignments", href: "/student/assignments", icon: FileText, roles: ["student"], section: "Learning" },
  { title: "Attendance", href: "/student/attendance", icon: ClipboardCheck, roles: ["student"], section: "Learning" },
  { title: "Grades", href: "/student/grades", icon: BarChart3, roles: ["student"], section: "Learning" },
  { title: "AI Tutor", href: "/student/ai-tutor", icon: Sparkles, roles: ["student"], section: "Learning" },

  { title: "Dashboard", href: "/parent", icon: LayoutDashboard, roles: ["parent"], section: "Main" },
  { title: "Children", href: "/parent/children", icon: GraduationCap, roles: ["parent"], section: "Family" },
  { title: "Fees", href: "/parent/fees", icon: CreditCard, roles: ["parent"], section: "Family" },
  { title: "Messages", href: "/parent/messages", icon: MessageSquare, roles: ["parent"], section: "Family" },

  { title: "Calendar", href: "/events", icon: CalendarDays, roles: ["super_admin", "school_admin", "teacher", "student", "parent", "hr_staff", "finance_officer", "it_support", "librarian"], section: "Settings & Support" }
];
