import Link from "next/link";
import { ArrowLeft, Plus } from "lucide-react";
import { OperationsGenericTable } from "@/components/operations/OperationsGenericTable";
import { OperationsRecordForm } from "@/components/operations/OperationsRecordForm";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { loadOperationsModule } from "@/features/operations/queries";

export async function BursaryReceiptsWorkspace() {
  const receipts = await loadOperationsModule("bursary", "receipts");
  if (!receipts) return null;
  const total = receipts.records.reduce((sum, record) => sum + Number(record.amount ?? 0), 0);

  return (
    <div className="reference-workspace space-y-6">
      <div className="ref-actions"><Link className="ref-button ref-button-secondary" href="/bursary"><ArrowLeft className="size-4" aria-hidden />Cashier desk</Link><a className="ref-button ref-primary" href="#new-receipt"><Plus className="size-4" aria-hidden />Record receipt</a></div>
      <section className="ref-stats"><div className="ref-stat"><span>Total receipts</span><strong>{receipts.count}</strong><p>All recorded bursary receipts</p></div><div className="ref-stat"><span>Total value</span><strong>GHS {total.toLocaleString("en-GH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</strong><p>Visible receipt register</p></div></section>
      <Card id="new-receipt"><CardHeader><CardTitle>Record receipt</CardTitle><p className="text-sm font-semibold text-[var(--portal-muted)]">Receipt numbers are generated by the server and the record is attributed to the signed-in cashier.</p></CardHeader><CardContent><OperationsRecordForm workspaceKey="bursary" moduleKey="receipts" moduleLabel="Receipt" fields={receipts.module.createFields ?? []} /></CardContent></Card>
      <Card><CardHeader><CardTitle>Receipt register</CardTitle><p className="text-sm font-semibold text-[var(--portal-muted)]">Search by receipt, student ID, payer, service, reference, or status.</p></CardHeader><CardContent><OperationsGenericTable records={receipts.records} fields={receipts.module.fields} searchFields={receipts.module.searchFields} /></CardContent></Card>
    </div>
  );
}
